docno="lists-014-11627495"
received="Tue Mar  2 01:45:43 2004"
isoreceived="20040302064543"
sent="Mon, 1 Mar 2004 22:36:08 0800"
isosent="20040302063608"
name="John L. Clark"
email="jlc6@po.cwru.edu"
subject="Bug ignoring RDF/XML xml:base?"
id="20040302063608.GA1383@bottle.cs.nps.navy.mil"
charset="usascii"
expires="1"

To:public-cwm-bugs@w3.org


To whom it may concern:

This may not be a bug with CWM, and may instead by user error, but it
seems like CWM is not correctly taking advantage of xml:base information
in the RDF/XML serialization.  To whit, with an RDF/XML baseline of:

    <rdf:RDF 
        xmlns:project="http://through.dnsalias.net/2004/project/"
        xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xml:base="http://through.dnsalias.net/2003/research/jclark/requirements.xml">

        <project:Article rdf:about="">
        </project>
    </rdf:RDF>

Then using:

    # cwm.py --rdf file.rdf

We get:

    <rdf:RDF xmlns="file:/path/to/file.rdf#"
        xmlns:project="http://through.dnsalias.net/2004/project/"
        xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

        <project:Article rdf:about="">
        </project>
    </rdf:RDF>

In particular, if I am correct in my interpretation of the RDF spec, the
statement in the second information set does not refer to the same
resource as that in the first information set.  As a minor secondary
issue, the default xmlns comes out of nowhere.

Thank you, and take care,

    John L. Clark




