docno="lists-099-12720069"
received="Mon Jan 26 03:28:18 2004"
isoreceived="20040126082818"
sent="Mon, 26 Jan 2004 02:28:17 -0600"
isosent="20040126082817"
name="Dan Connolly"
email="connolly@w3.org"
subject="crypto, n3String rotten?"
id="1075105697.8153.57.camel@dirk.dm93.org"
expires="-1"

To: Tim Berners-Lee<timbl@w3.org>
Cc: www-archive+n3bugs@w3.org, Sandro Hawke<sandro@w3.org>



I get

...
  File "/home/w3.org/w3ccvs/WWW/2000/10/swap/pretty.py", line 312, in
_scan
    self._scan(y, x)
  File "/home/w3.org/w3ccvs/WWW/2000/10/swap/pretty.py", line 312, in
_scan
    self._scan(y, x)
  File "/home/w3.org/w3ccvs/WWW/2000/10/swap/pretty.py", line 312, in
_scan
    self._scan(y, x)
  File "/home/w3.org/w3ccvs/WWW/2000/10/swap/pretty.py", line 293, in
_scan
    if verbosity() > 98: progress("scanning %s in context %s" %(`x`,
`context`),
RuntimeError: maximum recursion depth exceeded

if I do:

2000/10/swap$ python cwm.py test/crypto/test-n3String.n3 --think

I was getting
  'Private key not available in this object'
and unicode string exceptions in RSAKey.sign,
but I think I fixed those (cwm_crypto.py,v 1.8).

But I don't think I'm up to the challenge of debugging pretty.py .


-- 
Dan Connolly, W3C http://www.w3.org/People/Connolly/



