docno="lists-099-5677584"
received="Sun Mar  2 06:57:41 2003"
isoreceived="20030302115741"
sent="Sun, 2 Mar 2003 12:56:35 +0100"
isosent="20030302115635"
name="Jos De_Roo"
email="jos.deroo@agfa.com"
subject="Re: a testcase where we had existentials in the conclusion"
id="OFB2E4F67A.2C4C356D-ONC1256CDD.00414B75-C1256CDD.0041B056@agfa.be"
charset="us-ascii"
inreplyto="a testcase where we had existentials in the conclusion"
expires="-1"

To:"Dan Connolly<connolly"<connolly@w3.org>
Cc: Jos De_Roo<jos.deroo@agfa.com>, Sandro Hawke<sandro@w3.org>, Tim Berners-Lee<timbl@w3.org>,www-archive@w3.org




Dan, it's another problem; I see

amdus@VAM969 ~/w3ccvs/WWW/2000/10/swap
$ cvs update -d LX
Enter passphrase for RSA key '/cygdrive/c/.ssh/identity':
? LX/old/rdf.pyc
? LX/old/toShortNames.pyc
? LX/old/__init__.pyc
cvs server: Updating LX
U LX/URI.py
cvs update: move away LX/uri.py; it is in the way
C LX/uri.py
cvs server: Updating LX/engine
cvs server: Updating LX/language
cvs server: Updating LX/old
cvs server: Updating LX/support
cvs server: Updating LX/test


and it's because I'm on cygwin where
LX/URI.py and uri.py are the same
so it's now OK and working after I did

amdus@VAM969 ~/w3ccvs/WWW/2000/10/swap
$ rm LX/URI.py

amdus@VAM969 ~/w3ccvs/WWW/2000/10/swap
$ cvs update LX/uri.py
Enter passphrase for RSA key '/cygdrive/c/.ssh/identity':
U LX/uri.py

-- ,
Jos De Roo, AGFA http://www.agfa.com/w3c/jdroo/


                                                                                                                   
                    Dan Connolly                                                                                   
                    <connolly@w3.o       To:     Jos De_Roo/AMDUS/MOR/Agfa-NV/BE/BAYER@AGFA                        
                    rg>                  cc:     www-archive@w3.org, Tim Berners-Lee <timbl@w3.org>, Sandro Hawke  
                                          <sandro@w3.org>                                                          
                    2003-03-01           Subject:     Re: a testcase where we had existentials in the conclusion   
                    11:57 PM                                                                                       
                                                                                                                   
                                                                                                                   




On Sat, 2003-03-01 at 16:15, Jos De_Roo wrote:
[...]
> PS tested with a previous cwm as the latest cwm on my laptop gives
> Traceback (most recent call last):
>   File "/w3ccvs/WWW/2000/10/swap/cwm.py", line 58, in ?
>     import LX.engine.llynInterface
>   File "/w3ccvs/WWW/2000/10/swap\LX\engine\llynInterface.py", line 18, in
?
>     import LX.uri
> ImportError: No module named uri

try:

% cvs update -d LX

You're not the first to trip over this.

--
Dan Connolly, W3C http://www.w3.org/People/Connolly/



