docno="lists-098-14323002"
received="Wed Sep  4 16:09:35 2002"
isoreceived="20020904200935"
sent="Wed, 4 Sep 2002 16:09:29 -0400 (EDT)"
isosent="20020904200929"
name="Charles McCathieNevile"
email="charles@w3.org"
subject="Runtime error..."
id="Pine.LNX.4.30.0209041605360.1744-100000@tux.w3.org"
charset="US-ASCII"
expires="-1"

To: Tim Berners-Lee<timbl@w3.org>, Dan Connolly<connolly@w3.org>,<www-archive+n3bugs@w3.org>



Tried to replicate Dan's stuff making groups.rdf (the list of working group
deliverables published).

I checked out the bits of the site that I needed, (mem-news, swap,
Member/Mail...) apt-get installed python, downloaded saxon, and said make.

It thought for a long time, and this is what it said:

[localhost:2000/04/mem-news] charles% make
/sw/bin/python ../../../2000/10/swap/cwm.py --rdf groups-redundant.rdf \
--n3 ../../../2000/10/swap/test/sameThing.n3 ../../../2000/10/swap/pim/contact.n3 \
--think \
--apply=../../../2000/10/swap/test/forgetDups.n3 \
--purge --bySubject --rdf=c >groups.rdf
/sw/bin/python ../../../2000/10/swap/cwm.py --quiet \
--rdf groups.rdf \
--filter=group-leads-filter.n3 \
--rdf >group-leads.rdf
Traceback (most recent call last):
  File "../../../2000/10/swap/cwm.py", line 656, in ?
    doCommand()
  File "../../../2000/10/swap/cwm.py", line 549, in doCommand
    _store.loadURI(_uri)
  File "../../../2000/10/swap/llyn.py", line 1198, in loadURI
    p.load(uri)
  File "../../../2000/10/swap/notation3.py", line 165, in load
    self.feed(netStream.read())     # @ May be big - buffered in memory!
  File "../../../2000/10/swap/notation3.py", line 186, in feed
    i = self.directiveOrStatement(str,j)
  File "../../../2000/10/swap/notation3.py", line 199, in
directiveOrStatement
    j = self.statement(str, i)
  File "../../../2000/10/swap/notation3.py", line 284, in statement
    j = self.property_list(str, i, r[0])
  File "../../../2000/10/swap/notation3.py", line 537, in property_list
    i = self.object_list(str, j, objs)
  File "../../../2000/10/swap/notation3.py", line 555, in object_list
    i = self.object(str, i, res)
  File "../../../2000/10/swap/notation3.py", line 708, in object
    j = self.subject(str, i, res)
  File "../../../2000/10/swap/notation3.py", line 290, in subject
    return self.item(str, i, res)
  File "../../../2000/10/swap/notation3.py", line 363, in item
    return self.path(str, i, res)
  File "../../../2000/10/swap/notation3.py", line 368, in path
    j = self.nodeOrLiteral(str, i, res)
  File "../../../2000/10/swap/notation3.py", line 729, in nodeOrLiteral
    j = self.node(str, i, res)
  File "../../../2000/10/swap/notation3.py", line 418, in node
    if subj is None: subj=self._sink.newBlankNode(self._context)
  File "../../../2000/10/swap/RDFSink.py", line 217, in newBlankNode
    return self.newExistential(context)
  File "../../../2000/10/swap/RDFSink.py", line 231, in newExistential
    self.makeStatement((context,
  File "../../../2000/10/swap/llyn.py", line 1207, in makeStatement
    q = ( self.intern(tuple[CONTEXT]),
  File "../../../2000/10/swap/llyn.py", line 1050, in intern
    result = r.internFrag(urirefString[hash+1:], Anonymous)
  File "../../../2000/10/swap/thing.py", line 207, in internFrag
    raise RuntimeError("Oops.. %s exists already but not with type %s"%(f,
thetype))
RuntimeError: Oops.. _g0 exists already but not with type thing.Anonymous
make: *** [group-leads.rdf] Error 1


-- 
Charles McCathieNevile  http://www.w3.org/People/Charles  tel: +61 409 134 136
SWAD-E http://www.w3.org/2001/sw/Europe ------------ WAI http://www.w3.org/WAI
 21 Mitchell street, FOOTSCRAY Vic 3011, Australia  fax(fr): +33 4 92 38 78 22
 W3C, 2004 Route des Lucioles, 06902 Sophia Antipolis Cedex, France



