docno="lists-099-10910083"
received="Fri Feb 13 08:39:52 2004"
isoreceived="20040213133952"
sent="Fri, 13 Feb 2004 08:39:38 -0500"
isosent="20040213133938"
name="Tim Berners-Lee"
email="timbl@w3.org"
subject="Re: crypto, n3String rotten?"
id="1193A441-5E2A-11D8-B17D-000A9580D8C0@w3.org"
charset="US-ASCII"
inreplyto="1075105697.8153.57.camel&#64;dirk.dm93.org"
expires="-1"


Cc: Sandro Hawke<sandro@w3.org>, www-archive+n3bugs@w3.org
To: Dan Connolly<connolly@w3.org>


Dan,

That was a problem wit the use of "this" in the crypto code -- it was 
used in anger instead of just in to qualify things.  It is a reference 
to the formula itself, which is not something which I think we should 
keep for general use.
I plan to rewrite the application so that it doesn't use this.  It 
doesn't really need to - it was just interesting way fr expressing 
things at the time.

In other words, instead of saying "This is a certificate" you can say 
"There is a certificate", and that makes it a certficateDocument, no 
big deal.

One doesn't have to say "I hereby declare the bridge open" -- you can 
say "the bridge is open".

Tim
On Jan 26, 2004, at 3:28, Dan Connolly wrote:

> I get
>
> ...
>   File "/home/w3.org/w3ccvs/WWW/2000/10/swap/pretty.py", line 312, in
> _scan
>     self._scan(y, x)
>   File "/home/w3.org/w3ccvs/WWW/2000/10/swap/pretty.py", line 312, in
> _scan
>     self._scan(y, x)
>   File "/home/w3.org/w3ccvs/WWW/2000/10/swap/pretty.py", line 312, in
> _scan
>     self._scan(y, x)
>   File "/home/w3.org/w3ccvs/WWW/2000/10/swap/pretty.py", line 293, in
> _scan
>     if verbosity() > 98: progress("scanning %s in context %s" %(`x`,
> `context`),
> RuntimeError: maximum recursion depth exceeded
>
> if I do:
>
> 2000/10/swap$ python cwm.py test/crypto/test-n3String.n3 --think
>
> I was getting
>   'Private key not available in this object'
> and unicode string exceptions in RSAKey.sign,
> but I think I fixed those (cwm_crypto.py,v 1.8).
>
> But I don't think I'm up to the challenge of debugging pretty



